"""Remove progress tracking feature

Revision ID: aedb32ca6ce3
Revises: eff28a88164d
Create Date: 2025-04-14 19:07:20.911859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aedb32ca6ce3'
down_revision = 'eff28a88164d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_resource_progress')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_resource_progress',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('progress_status_enum', postgresql.ENUM('Not Started', 'In Progress', 'Completed', name='progressstatusenum'), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name='user_resource_progress_resource_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_resource_progress_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'resource_id', name='user_resource_progress_pkey')
    )
    # ### end Alembic commands ###
